jobs: 30000 
cluster: "sbatch -A investor -p mem -J {rule}.job --qos mem --nodes=1  --mem 32G --time 14-23:59:59 -o logs/cluster/{rule}_%A.out -e logs/cluster/{rule}_%A.err"
default-resources: [cpus=32]
