#!/bin/env python

include: "../rules/fastqc.smk"
include: "../rules/align.smk"
include: "../rules/bam2bed.smk"
include: "../rules/sort_filter.smk"
include: "../rules/length_distribution.smk"
include: "../rules/plot_length.smk"
#include: "../rules/length_mode.smk"
include: "../rules/sep_strands.smk"
#include: "../rules/bed2fasta.smk"
#include: "../rules/nucleotide_table.smk"
#include: "../rules/plot_nuc.smk"
include: "../rules/genomecov.smk"
include: "../rules/bedGraphToBigWig.smk"
include: "../rules/simulation.smk"
#include: "../rules/nucleotide_table_sim.smk"
#include: "../rules/plot_nuc_sim.smk"


