xr:
  samples: 
    - "Hela15X2_comb"
    - "Hela35X3_comb"
    - "HXA64_comb"
    - "HXE64_comb"
    - "HXL64_comb"
    - "HXAC_comb"
    - "HXEC_comb"
    - "HXLC_comb"

ds:
  samples: 
    - "HelaD1_5R2h2_comb"
    - "HelaD3_5R2h2_comb"
    - "HDA64_comb"
    - "HDE64_comb"
    - "HDL64_comb"
    - "HDAC_comb"
    - "HDEC_comb"
    - "HDLC_comb"

edu:
  samples: 
    - "R21061297-EdUrep-2hrls_combined"
    - "R21061297-EdUrep-4hrls_combined"
    - "R21061297-EdUrep-UV1-5hrls_combined"
    - "R21061297-EdUrep-UV3-5hrls_combined"
    - "R21061297-EdUrep-inp2hrls_combined"
    - "R21061297-EdUrep-inp4hrls_combined" 
    - "R21061297-EdUrep-inpUV1-5hrls_combined" 
    - "R21061297-EdUrep-inpUV3-5hrls_combined"
    - "R21071354-EdUrep2-2hrls2_combined"
    - "R21071354-EdUrep2-4hrls2_combined"
    - "R21071354-EdUrep2-inp2hrls2_combined"
    - "R21071354-EdUrep2-inp4hrls2_combined"
    - "R21071354-EdUrep2-UV1-5hrls2_combined"
    - "R21071354-EdUrep2-UV3-5hrls2_combined"
    - "R21071354-EdUrep2-inpUV1-5hrls2_combined"
    - "R21071354-EdUrep2-inpUV3-5hrls2_combined"
    - "R21102739-EdUrep3-inpUV1-5hrls3_combined"
    - "R21102739-EdUrep3-inpUV3-5hrls3_combined"
    - "R21102739-EdUrep3-UV1-5hrls3_combined"
    - "R21102739-EdUrep3-UV3-5hrls3_combined"
  srr: 
    enabled: False
    codes:
      - ""

okseq:
  samples:
    - "IMR90"
    - "GM06990"
    - "HeLa"
  srr: 
    enabled: True
    codes:
      - "ERR2760855"
      - "SRR2913063"
      - "SRR2913039"

mutation:
  samples:
    - "melanoma"

regions:
  - "iz_hela_repdomains_uv_mean0.5_windows_201_100"
  - "chromhmm_hela_repdomains_uv_mean0.5"
  - "repdomains_uv_mean0.5_windows_201_10000"
  - "repdomains_uv_mean0.5"
  

region_file:
  - "iz_hela_repdomains_uv_mean0.5_windows_201_100.bed"
  - "chromhmm_hela_repdomains_uv_mean0.5.bed"
  - "repdomains_uv_mean0.5_windows_201_10000.bed"
  - "repdomains_uv_mean0.5.bed"

region_comb_opt:
  - "-"
  - "notCombine" 
  - "-"
  - "notCombine"

regions_mut:
  - "iz_hela_to_gm_imr_repdomains_uv_mean0.5_with_scores_windows_201_100"
  - "iz_hela_to_gm_imr_repdomains_uv_mean0.5_windows_201_100"
  - "iz_hela_no_overlap_repdomains_uv_mean0.5_windows_201_100"

region_mut_file:
  - "iz_hela_to_gm_imr_repdomains_uv_mean0.5_with_scores_windows_201_100.bed"
  - "iz_hela_to_gm_imr_repdomains_uv_mean0.5_windows_201_100.bed"
  - "iz_hela_no_overlap_repdomains_uv_mean0.5_windows_201_100.bed"

region_mut_comb_opt:  
  - "'-score T -strand T'"
  - "'-score T -strand T'"
  - "'-score T -strand T'"