build: "hg19"

xr:
  samples: 
    #- "HXA64A1_ATCACG"
    #- "HXA64B7_CAGATC"
    #- "HXACA4_TGACCA"
    #- "HXACB10_TAGCTT"
    #- "HXE64A2_CGATGT"
    #- "HXE64B8_ACTTGA"
    #- "HXECA5_ACAGTG"
    #- "HXECB11_GGCTAC"
    #- "HXL64A3_TTAGGC"
    #- "HXL64B9_GATCAG"
    #- "HXLCA6_GCCAAT"
    #- "HXLCB12_CTTGTA"
    #- "R19026421-2019XR1-Hela15X2_combined_R1"
    #- "R19026421-2019XR1-Hela35X3_combined_R1"
    #- "R19033030-2019XR3-Hela15X7_combined_R1"
    #- "R19033030-2019XR3-Hela35X8_combined_R1"
    - "Hela15X2_comb"
    - "Hela35X3_comb"
    - "HXA64_comb"
    - "HXE64_comb"
    - "HXL64_comb"
    - "HXAC_comb"
    - "HXEC_comb"
    - "HXLC_comb"

ds:
  samples: 
    #- "HDA64A1_ATCACG"
    #- "HDA64B19_GTGAAA"
    #- "HDACA6_GCCAAT"
    #- "HDACB23_GAGTGG"
    #- "HDE64A4_TGACCA"
    #- "HDE64B20_GTGGCC"
    #- "HDECA10_TAGCTT"
    #- "HDECB25_ACTGAT"
    #- "HDL64A5_ACAGTG"
    #- "HDL64B22_CGTACG"
    #- "HDLCA12_CTTGTA"
    #- "HDLCB27_ATTCCT"
    #- "NT4H1-CT5H2-HelaD1-5R2h2_combined"
    #- "XT4H1-CT5H2-HelaD3-5R2h2_combined"
    #- "R19029847-HD2TCD4-HelaD1-5R2h1_combined"
    #- "R19029847-HD2TCD4-HelaD3-5R2h1_combined"
    - "HelaD1_5R2h2_comb"
    - "HelaD3_5R2h2_comb"
    - "HDA64_comb"
    - "HDE64_comb"
    - "HDL64_comb"
    - "HDAC_comb"
    - "HDEC_comb"
    - "HDLC_comb"

edu:
  samples: 
    - "R21061297-EdUrep-2hrls_combined"
    - "R21061297-EdUrep-4hrls_combined"
    - "R21061297-EdUrep-UV1-5hrls_combined"
    - "R21061297-EdUrep-UV3-5hrls_combined"
    - "R21061297-EdUrep-inp2hrls_combined"
    - "R21061297-EdUrep-inp4hrls_combined" 
    - "R21061297-EdUrep-inpUV1-5hrls_combined" 
    - "R21061297-EdUrep-inpUV3-5hrls_combined"
    - "R21071354-EdUrep2-2hrls2_combined"
    - "R21071354-EdUrep2-4hrls2_combined"
    - "R21071354-EdUrep2-inp2hrls2_combined"
    - "R21071354-EdUrep2-inp4hrls2_combined"
    - "R21071354-EdUrep2-UV1-5hrls2_combined"
    - "R21071354-EdUrep2-UV3-5hrls2_combined"
    - "R21071354-EdUrep2-inpUV1-5hrls2_combined"
    - "R21071354-EdUrep2-inpUV3-5hrls2_combined"
    - "R21102739-EdUrep3-inpUV1-5hrls3_combined"
    - "R21102739-EdUrep3-inpUV3-5hrls3_combined"
    - "R21102739-EdUrep3-UV1-5hrls3_combined"
    - "R21102739-EdUrep3-UV3-5hrls3_combined"
  srr: 
    enabled: False
    codes:
      - ""

okseq:
  samples:
    - "IMR90"
    - "GM06990"
    - "HeLa"
  srr: 
    enabled: True
    codes:
      - "ERR2760855"
      - "SRR2913063"
      - "SRR2913039"

mutation:
  samples:
    - "melanoma"

regions:
  - "iz_hela_repdomains_uv_mean0.5_windows_201_100"
  - "chromhmm_hela_repdomains_uv_mean0.5"
  - "repdomains_uv_mean0.5_windows_201_10000"
  - "repdomains_uv_mean0.5"
  

region_file:
  - "iz_hela_repdomains_uv_mean0.5_windows_201_100.bed"
  - "chromhmm_hela_repdomains_uv_mean0.5.bed"
  - "repdomains_uv_mean0.5_windows_201_10000.bed"
  - "repdomains_uv_mean0.5.bed"

region_comb_opt:
  - "-"
  - "notCombine" 
  - "-"
  - "notCombine"

regions_mut:
  - "iz_hela_to_gm_imr_repdomains_uv_mean0.5_with_scores_windows_201_100"
  - "iz_hela_to_gm_imr_repdomains_uv_mean0.5_windows_201_100"
  - "iz_hela_no_overlap_repdomains_uv_mean0.5_windows_201_100"

region_mut_file:
  - "iz_hela_to_gm_imr_repdomains_uv_mean0.5_with_scores_windows_201_100.bed"
  - "iz_hela_to_gm_imr_repdomains_uv_mean0.5_windows_201_100.bed"
  - "iz_hela_no_overlap_repdomains_uv_mean0.5_windows_201_100.bed"

region_mut_comb_opt:  
  - "'-score T -strand T'"
  - "'-score T -strand T'"
  - "'-score T -strand T'"