
sample_xr:
  - "HXA64A1_ATCACG"
  - "HXA64B7_CAGATC"
  - "HXACA4_TGACCA"
  - "HXACB10_TAGCTT"
  - "HXE64A2_CGATGT"
  - "HXE64B8_ACTTGA"
  - "HXECA5_ACAGTG"
  - "HXECB11_GGCTAC"
  - "HXL64A3_TTAGGC"
  - "HXL64B9_GATCAG"
  - "HXLCA6_GCCAAT"
  - "HXLCB12_CTTGTA"
  - "R19026421-2019XR1-Hela15X2_combined_R1"
  - "R19026421-2019XR1-Hela35X3_combined_R1"
  - "R19033030-2019XR3-Hela15X7_combined_R1"
  - "R19033030-2019XR3-Hela35X8_combined_R1"
  - "Hela15X2_comb"
  - "Hela35X3_comb"
  - "HXA64_comb"
  - "HXE64_comb"
  - "HXL64_comb"
  - "HXAC_comb"
  - "HXEC_comb"
  - "HXLC_comb"

sample_ds:
  - "HDA64A1_ATCACG"
  - "HDA64B19_GTGAAA"
  - "HDACA6_GCCAAT"
  - "HDACB23_GAGTGG"
  - "HDE64A4_TGACCA"
  - "HDE64B20_GTGGCC"
  - "HDECA10_TAGCTT"
  - "HDECB25_ACTGAT"
  - "HDL64A5_ACAGTG"
  - "HDL64B22_CGTACG"
  - "HDLCA12_CTTGTA"
  - "HDLCB27_ATTCCT"
  - "NT4H1-CT5H2-HelaD1-5R2h2_combined"
  - "XT4H1-CT5H2-HelaD3-5R2h2_combined"
  - "R19029847-HD2TCD4-HelaD1-5R2h1_combined"
  - "R19029847-HD2TCD4-HelaD3-5R2h1_combined"
  - "HelaD1_5R2h2_comb"
  - "HelaD3_5R2h2_comb"
  - "HDA64_comb"
  - "HDE64_comb"
  - "HDL64_comb"
  - "HDAC_comb"
  - "HDEC_comb"
  - "HDLC_comb"

sample_input: 
  - "R19040024-HelainputD-Hl15R2hID_combined"

sample_edu: 
  - "R21061297-EdUrep-2hrls_combined"
  - "R21061297-EdUrep-4hrls_combined"
  - "R21061297-EdUrep-UV1-5hrls_combined"
  - "R21061297-EdUrep-UV3-5hrls_combined"
  - "R21061297-EdUrep-inp2hrls_combined"
  - "R21061297-EdUrep-inp4hrls_combined" 
  - "R21061297-EdUrep-inpUV1-5hrls_combined" 
  - "R21061297-EdUrep-inpUV3-5hrls_combined"
  - "R21071354-EdUrep2-2hrls2_combined"
  - "R21071354-EdUrep2-4hrls2_combined"
  - "R21071354-EdUrep2-inp2hrls2_combined"
  - "R21071354-EdUrep2-inp4hrls2_combined"
  - "R21071354-EdUrep2-UV1-5hrls2_combined"
  - "R21071354-EdUrep2-UV3-5hrls2_combined"
  - "R21071354-EdUrep2-inpUV1-5hrls2_combined"
  - "R21071354-EdUrep2-inpUV3-5hrls2_combined"
  - "R21102739-EdUrep3-inpUV1-5hrls3_combined"
  - "R21102739-EdUrep3-inpUV3-5hrls3_combined"
  - "R21102739-EdUrep3-UV1-5hrls3_combined"
  - "R21102739-EdUrep3-UV3-5hrls3_combined"

sample_okseq:
  - "cem"

sample_mutation:
  - "melanoma"

sample_markers:
  - ENCFF916VLX_h3k79me2_hela
  - ENCFF803UAY_h3k4me3_hela
  - ENCFF723WDR_h3k9ac_hela
  - ENCFF582MED_h3k36me3_hela
  - ENCFF572NWJ_h3k4me1_hela
  - ENCFF563OMA_h3k9me3_hela
  - ENCFF526HPH_h3k4me3_hela
  - ENCFF447CLK_h3k4me3_hela
  - ENCFF410YQK_h3k27me3_hela
  - ENCFF252BLX_h3k27me3_hela
  - ENCFF144EOJ_h3k27ac_hela
  - ENCFF108DAJ_h3k4me2_hela
  - ENCFF094MFL_h2afz_hela
  - ENCFF069BQG_h4k20me1_hela
  - ENCFF056OVB_h3k36me3_hela

build: "hg19"

regions:
  #- "iz_hela_windows_201_100"
  #- "iz_repdomains_hela_widows_201_100"
  #- "iz_gm06990_repdomains_hela_widows_201_100"
  #- "chromhmm_repdomains_hela_windows"
  #- "chromhmm_repdomains_hela_windows_chr"
  #- "repdomains_hela_windows_201_10000"
  #- "repdomains_hela"
  #- "sns.seq.rep1_int2hi.rfd_plus_hela_repdomains_windows_201_100"
  #- "sns.seq.rep1_int2hi.rfd_minus_hela_repdomains_windows_201_100"
  #- "sns.seq.rep1_int2initiation.zones_hela_repdomains_windows_201_100"
  #- "initiation.zones_int2sns.seq.rep1_hela_repdomains_windows_201_100"
  #- "sns.seq.rep1_int2initiation.zones_hela_repdomains_windows_51_100"
  #- "sns.seq.rep1.hela_repdomains_no_overlap_windows_201_100"
  #- "sns.seq.rep1.hela_repdomains_no_overlap_windows_51_100"
  #- "iz_repdomains_uv_hela_windows_201_100"
  #- "iz_repdomains_hela_windows_201_100"
  #- "repdomains_windows_201_10000"
  #- "repdomains_uv_windows_201_10000"
  #- "repdomains"
  #- "repdomains_uv"
  #- "sns-seq_repdomains_uv_hela_windows_201_100"
  #- "sns-seq_repdomains_hela_windows_201_100"
  - "sns-seq_repdomains_uv_m0.5_hela_windows_51_100"
  - "sns-seq_repdomains_m0.5_hela_windows_51_100"
  - "repdomains_mean0.5_windows_201_10000"
  - "repdomains_uv_mean0.5_windows_201_10000"
  - "iz_repdomains_uv_m0.5_hela_windows_201_100"
  - "iz_repdomains_m0.5_hela_windows_201_100"

region_file:
  #- "initiation.zones.hela_windows_201_100.bed"
  #- "initiation.zones.repdomains.hela_windows_201_100.bed"
  #- "IZ.gm06990_repdomains_windows_201_100.bed"
  #- "chromhmm.repdomains.hela_windows.bed"
  #- "chromhmm.repdomains.hela_windows.bed"
  #- "repdomains.hela_windows_201_10000.bed"
  #- "repdomains.hela.bed"
  #- "sns.seq.rep1_int2hi.rfd_plus_hela_repdomains_windows_201_100.bed"
  #- "sns.seq.rep1_int2hi.rfd_minus_hela_repdomains_windows_201_100.bed"
  #- "sns.seq.rep1_int2initiation.zones_hela_repdomains_windows_201_100.bed"
  #- "initiation.zones_int2sns.seq.rep1_hela_repdomains_windows_201_100.bed"
  #- "sns.seq.rep1_int2initiation.zones_hela_repdomains_windows_51_100.bed"
  #- "sns.seq.rep1.hela_repdomains_no_overlap_windows_201_100.bed"
  #- "sns.seq.rep1.hela_repdomains_no_overlap_windows_51_100.bed"
  #- "iz_repdomains_uv_hela_windows_201_100.bed"
  #- "iz_repdomains_hela_windows_201_100.bed"
  #- "repdomains_windows_201_10000.bed"
  #- "repdomains_uv_windows_201_10000.bed"
  #- "repdomains.bed"
  #- "repdomains_uv.bed"
  #- "sns-seq_repdomains_uv_hela_windows_201_100.bed"
  #- "sns-seq_repdomains_hela_windows_201_100.bed"
  - "sns-seq_repdomains_uv_m0.5_hela_windows_51_100.bed"
  - "sns-seq_repdomains_m0.5_hela_windows_51_100.bed"
  - "repdomains_mean0.5_windows_201_10000.bed"
  - "repdomains_uv_mean0.5_windows_201_10000.bed"
  - "iz_repdomains_uv_m0.5_hela_windows_201_100.bed"
  - "iz_repdomains_m0.5_hela_windows_201_100.bed"

region_comb_opt:
  #- "-"
  #- "-"
  #- "-"
  #- "-strand T" 
  #- "-strand T -chr T"
  #- "-"
  #- "notCombine"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "notCombine"
  #- "notCombine"
  #- "-"
  #- "-"
  - "-"
  - "-"
  - "-"
  - "-"
  - "-"
  - "-"

regions_mut:
  - "hela_no_overlap_repdomains_windows_201_100"
  - "sns.seq.rep1_int2hi.rfd_plus_hela_repdomains_windows_201_100"
  - "sns.seq.rep1_int2hi.rfd_minus_hela_repdomains_windows_201_100"
  - "sns.seq.rep1_int2initiation.zones_hela_repdomains_windows_201_100"
  - "initiation.zones_int2sns.seq.rep1_hela_repdomains_windows_201_100"
  - "sns.seq.rep1_int2initiation.zones_hela_repdomains_windows_51_100"
  - "sns.seq.rep1.hela_repdomains_no_overlap_windows_201_100"
  - "sns.seq.rep1.hela_repdomains_no_overlap_windows_51_100"


region_mut_file:
  - "hela_no_overlap_repdomains_windows_201_100.bed"
  - "sns.seq.rep1_int2hi.rfd_plus_hela_repdomains_windows_201_100.bed"
  - "sns.seq.rep1_int2hi.rfd_minus_hela_repdomains_windows_201_100.bed"
  - "sns.seq.rep1_int2initiation.zones_hela_repdomains_windows_201_100.bed"
  - "initiation.zones_int2sns.seq.rep1_hela_repdomains_windows_201_100.bed"
  - "sns.seq.rep1_int2initiation.zones_hela_repdomains_windows_51_100.bed"
  - "sns.seq.rep1.hela_repdomains_no_overlap_windows_201_100.bed"
  - "sns.seq.rep1.hela_repdomains_no_overlap_windows_51_100.bed"

region_mut_comb_opt:  
  - "-score T -strand T"
  - "-score T -strand T"
  - "-score T -strand T"
  - "-score T -strand T"
  - "-score T -strand T"
  - "-score T -strand T"
  - "-score T -strand T"
  - "-score T -strand T"
 
     


