
sample_xr:
  - ""

sample_ds:
  - "HDA64A1_ATCACG_sub10k"

sample_input: 
  - "R19040024-HelainputD-Hl15R2hID_combined"

sample_okseq:
  - "cem"

sample_mutation:
  - "melanoma"

build: "hg19"

regions:
  - "iz_hela_windows_201_100"

region_file:
  - "initiation.zones.hela_windows_201_100.bed"

region_comb_opt:
  - ""
