
sample_xr:
  - "HXA64A1_ATCACG"
  #- "HXA64B7_CAGATC"
  #- "HXACA4_TGACCA"
  #- "HXACB10_TAGCTT"
  #- "HXE64A2_CGATGT"
  #- "HXE64B8_ACTTGA"
  #- "HXECA5_ACAGTG"
  #- "HXECB11_GGCTAC"
  #- "HXL64A3_TTAGGC"
  #- "HXL64B9_GATCAG"
  #- "HXLCA6_GCCAAT"
  #- "HXLCB12_CTTGTA"
  #- "R19026421-2019XR1-Hela15X2_combined_R1"
  #- "R19026421-2019XR1-Hela35X3_combined_R1"
  #- "R19033030-2019XR3-Hela15X7_combined_R1"
  #- "R19033030-2019XR3-Hela35X8_combined_R1"

sample_ds:
  - "HDA64A1_ATCACG"
  #- "HDA64B19_GTGAAA"
  #- "HDACA6_GCCAAT"
  #- "HDACB23_GAGTGG"
  #- "HDE64A4_TGACCA"
  #- "HDE64B20_GTGGCC"
  #- "HDECA10_TAGCTT"
  #- "HDECB25_ACTGAT"
  #- "HDL64A5_ACAGTG"
  #- "HDL64B22_CGTACG"
  #- "HDLCA12_CTTGTA"
  #- "HDLCB27_ATTCCT"
  #- "NT4H1-CT5H2-HelaD1-5R2h2_combined"
  #- "XT4H1-CT5H2-HelaD3-5R2h2_combined"
  #- "R19029847-HD2TCD4-HelaD1-5R2h1_combined"
  #- "R19029847-HD2TCD4-HelaD3-5R2h1_combined"

sample_input: 
  - "R19040024-HelainputD-Hl15R2hID_combined"

sample_okseq:
  - "cem"

sample_edu:
  - "cem"

sample_mutation:
  - "melanoma"

build: "hg19"

regions:
  - "iz_hela_windows_201_100"
  - "iz_repdomains_hela_widows_201_100"
  - "iz_gm06990_repdomains_hela_widows_201_100"
  - "chromhmm_repdomains_hela_windows"
  - "chromhmm_repdomains_hela_windows_chr"
  - "repdomains_hela_windows_201_10000"
  - "repdomains_hela"

region_file:
  - "initiation.zones.hela_windows_201_100.bed"
  - "initiation.zones.repdomains.hela_windows_201_100.bed"
  - "IZ.gm06990_repdomains_windows_201_100.bed"
  - "chromhmm.repdomains.hela_windows.bed"
  - "chromhmm.repdomains.hela_windows.bed"
  - "repdomains.hela_windows_201_10000.bed"
  - "repdomains.hela.bed"

region_comb_opt:
  - ""
  - ""
  - ""
  - "-strand T" 
  - "-strand T -chr T"
  - ""
  - ""
