build: "hg19"

xr:
  samples: 
    - "HXA64A1_ATCACG"
    - "HXA64B7_CAGATC"
    - "HXACA4_TGACCA"
    - "HXACB10_TAGCTT"
    - "HXE64A2_CGATGT"
    - "HXE64B8_ACTTGA"
    - "HXECA5_ACAGTG"
    - "HXECB11_GGCTAC"
    - "HXL64A3_TTAGGC"
    - "HXL64B9_GATCAG"
    - "HXLCA6_GCCAAT"
    - "HXLCB12_CTTGTA"
    - "R19026421-2019XR1-Hela15X2_combined_R1"
    - "R19026421-2019XR1-Hela35X3_combined_R1"
    - "R19033030-2019XR3-Hela15X7_combined_R1"
    - "R19033030-2019XR3-Hela35X8_combined_R1"
    - "Hela15X2_comb"
    - "Hela35X3_comb"
    - "HXA64_comb"
    - "HXE64_comb"
    - "HXL64_comb"
    - "HXAC_comb"
    - "HXEC_comb"
    - "HXLC_comb"

ds:
  samples: 
    - "HDA64A1_ATCACG"
    - "HDA64B19_GTGAAA"
    - "HDACA6_GCCAAT"
    - "HDACB23_GAGTGG"
    - "HDE64A4_TGACCA"
    - "HDE64B20_GTGGCC"
    - "HDECA10_TAGCTT"
    - "HDECB25_ACTGAT"
    - "HDL64A5_ACAGTG"
    - "HDL64B22_CGTACG"
    - "HDLCA12_CTTGTA"
    - "HDLCB27_ATTCCT"
    - "NT4H1-CT5H2-HelaD1-5R2h2_combined"
    - "XT4H1-CT5H2-HelaD3-5R2h2_combined"
    - "R19029847-HD2TCD4-HelaD1-5R2h1_combined"
    - "R19029847-HD2TCD4-HelaD3-5R2h1_combined"
    - "HelaD1_5R2h2_comb"
    - "HelaD3_5R2h2_comb"
    - "HDA64_comb"
    - "HDE64_comb"
    - "HDL64_comb"
    - "HDAC_comb"
    - "HDEC_comb"
    - "HDLC_comb"

edu:
  samples: 
    - "R21061297-EdUrep-2hrls_combined"
    - "R21061297-EdUrep-4hrls_combined"
    - "R21061297-EdUrep-UV1-5hrls_combined"
    - "R21061297-EdUrep-UV3-5hrls_combined"
    - "R21061297-EdUrep-inp2hrls_combined"
    - "R21061297-EdUrep-inp4hrls_combined" 
    - "R21061297-EdUrep-inpUV1-5hrls_combined" 
    - "R21061297-EdUrep-inpUV3-5hrls_combined"
    - "R21071354-EdUrep2-2hrls2_combined"
    - "R21071354-EdUrep2-4hrls2_combined"
    - "R21071354-EdUrep2-inp2hrls2_combined"
    - "R21071354-EdUrep2-inp4hrls2_combined"
    - "R21071354-EdUrep2-UV1-5hrls2_combined"
    - "R21071354-EdUrep2-UV3-5hrls2_combined"
    - "R21071354-EdUrep2-inpUV1-5hrls2_combined"
    - "R21071354-EdUrep2-inpUV3-5hrls2_combined"
    - "R21102739-EdUrep3-inpUV1-5hrls3_combined"
    - "R21102739-EdUrep3-inpUV3-5hrls3_combined"
    - "R21102739-EdUrep3-UV1-5hrls3_combined"
    - "R21102739-EdUrep3-UV3-5hrls3_combined"
  srr: 
    enabled: False
    codes:
      - ""

okseq:
  samples:
    - "IMR90"
    - "GM06990"
    - "HeLa"
  srr: 
    enabled: False
    codes:
      - "ERR2760855"
      - "SRR2913060:SRR2913061:SRR2913062:SRR2913063"
      - "SRR2913036:SRR2913037:SRR2913038:SRR2913039:SRR2913040:SRR2913041:SRR2913042"

mutation:
  samples:
    - "melanoma"

methyl:
  samples:
    - "GSM3633947_ENCFF093WZD_methylation_state_at_CHG"
    - "GSM3633947_ENCFF474VQX_methylation_state_at_CHH"
    - "GSM3633947_ENCFF696OLO_methylation_state_at_CpG"

chipseq:
  samples:
    - HeLa_H2AFZ_A
    - HeLa_H3K27ac_A
    - HeLa_H3K27me3_A
    - HeLa_H3K27me3_B
    - HeLa_H3K36me3_A
    - HeLa_H3K36me3_B
    - HeLa_H3K4me1_A
    - HeLa_H3K4me2_A
    #- HeLa_H3K4me3_A
    - HeLa_H3K4me3_B
    - HeLa_H3K4me3_C
    - HeLa_H3K79me2_A
    - HeLa_H3K9ac_A
    - HeLa_H3K9me3_A
    - HeLa_H4K20me1_A
  srr: 
    enabled: False
    codes:
      - "SRR568260:SRR568261"
      - "SRR227445:SRR227446"
      - "SRR577392:SRR577393"
      - "SRR227472:SRR227473"
      - "SRR577429:SRR577430"
      - "SRR227505:SRR227506"
      - "SRR350914:SRR350915"
      - "SRR227556:SRR227557"
      #- "SRR5338596:SRR5338597:SRR5338598:SRR5338599:SRR5338600"
      - "SRR577378:SRR577379"
      - "SRR227441:SRR227442"
      - "SRR227413:SRR227414"
      - "SRR227602:SRR227603"
      - "SRR568254:SRR568255"
      - "SRR227456:SRR227457"

regions:
  #- "iz_hela_windows_201_100"
  #- "iz_repdomains_hela_widows_201_100"
  #- "iz_gm06990_repdomains_hela_widows_201_100"
  #- "chromhmm_repdomains_hela_windows"
  #- "chromhmm_repdomains_hela_windows_chr"
  #- "repdomains_hela_windows_201_10000"
  #- "repdomains_hela"
  #- "sns.seq.rep1_int2hi.rfd_plus_hela_repdomains_windows_201_100"
  #- "sns.seq.rep1_int2hi.rfd_minus_hela_repdomains_windows_201_100"
  #- "sns.seq.rep1_int2initiation.zones_hela_repdomains_windows_201_100"
  #- "initiation.zones_int2sns.seq.rep1_hela_repdomains_windows_201_100"
  #- "sns.seq.rep1_int2initiation.zones_hela_repdomains_windows_51_100"
  #- "sns.seq.rep1.hela_repdomains_no_overlap_windows_201_100"
  #- "sns.seq.rep1.hela_repdomains_no_overlap_windows_51_100"
  #- "iz_repdomains_uv_hela_windows_201_100"
  #- "iz_repdomains_hela_windows_201_100"
  #- "repdomains_windows_201_10000"
  #- "repdomains_uv_windows_201_10000"
  #- "repdomains"
  #- "repdomains_uv"
  #- "sns-seq_repdomains_uv_hela_windows_201_100"
  #- "sns-seq_repdomains_hela_windows_201_100"
  #- "sns-seq_repdomains_uv_m0.5_hela_windows_51_100"
  #- "sns-seq_repdomains_m0.5_hela_windows_51_100"
  #- "repdomains_mean0.5_windows_201_10000"
  #- "repdomains_uv_mean0.5_windows_201_10000"
  #- "iz_repdomains_uv_m0.5_hela_windows_201_100"
  #- "iz_repdomains_m0.5_hela_windows_201_100"
  #- "sns-seq_repdomains_uv_m0.5_hela_windows_21_1000"
  #- "sns-seq_repdomains_m0.5_hela_windows_21_1000"
  #- "iz_repdomains_uv_m0.5_hela_windows_21_1000"
  #- "iz_repdomains_m0.5_hela_windows_21_1000"
  - "iz_hela_repdomains_uv_mean0.5_windows_201_100"
  #- "chromhmm_hela_repdomains_uv_mean0.5"
  #- "chromhmm_hela_repdomains_uv_mean0.5_chr"
  #- "repdomains_uv_mean0.5_windows_201_10000"
  #- "repdomains_uv_mean0.5"

region_file:
  #- "initiation.zones.hela_windows_201_100.bed"
  #- "initiation.zones.repdomains.hela_windows_201_100.bed"
  #- "IZ.gm06990_repdomains_windows_201_100.bed"
  #- "chromhmm.repdomains.hela_windows.bed"
  #- "chromhmm.repdomains.hela_windows.bed"
  #- "repdomains.hela_windows_201_10000.bed"
  #- "repdomains.hela.bed"
  #- "sns.seq.rep1_int2hi.rfd_plus_hela_repdomains_windows_201_100.bed"
  #- "sns.seq.rep1_int2hi.rfd_minus_hela_repdomains_windows_201_100.bed"
  #- "sns.seq.rep1_int2initiation.zones_hela_repdomains_windows_201_100.bed"
  #- "initiation.zones_int2sns.seq.rep1_hela_repdomains_windows_201_100.bed"
  #- "sns.seq.rep1_int2initiation.zones_hela_repdomains_windows_51_100.bed"
  #- "sns.seq.rep1.hela_repdomains_no_overlap_windows_201_100.bed"
  #- "sns.seq.rep1.hela_repdomains_no_overlap_windows_51_100.bed"
  #- "iz_repdomains_uv_hela_windows_201_100.bed"
  #- "iz_repdomains_hela_windows_201_100.bed"
  #- "repdomains_windows_201_10000.bed"
  #- "repdomains_uv_windows_201_10000.bed"
  #- "repdomains.bed"
  #- "repdomains_uv.bed"
  #- "sns-seq_repdomains_uv_hela_windows_201_100.bed"
  #- "sns-seq_repdomains_hela_windows_201_100.bed"
  #- "sns-seq_repdomains_uv_m0.5_hela_windows_51_100.bed"
  #- "sns-seq_repdomains_m0.5_hela_windows_51_100.bed"
  #- "repdomains_mean0.5_windows_201_10000.bed"
  #- "repdomains_uv_mean0.5_windows_201_10000.bed"
  #- "iz_repdomains_uv_m0.5_hela_windows_201_100.bed"
  #- "iz_repdomains_m0.5_hela_windows_201_100.bed"
  #- "sns-seq_repdomains_uv_m0.5_hela_windows_21_1000.bed"
  #- "sns-seq_repdomains_m0.5_hela_windows_21_1000.bed"
  #- "iz_repdomains_uv_m0.5_hela_windows_21_1000.bed"
  #- "iz_repdomains_m0.5_hela_windows_21_1000.bed"
  - "iz_hela_repdomains_uv_mean0.5_windows_201_100.bed"
  #- "chromhmm_hela_repdomains_uv_mean0.5.bed"
  #- "chromhmm_hela_repdomains_uv_mean0.5.bed"
  #- "repdomains_uv_mean0.5_windows_201_10000.bed"
  #- "repdomains_uv_mean0.5.bed"

region_comb_opt:
  #- "-"
  #- "-"
  #- "-"
  #- "-strand T" 
  #- "-strand T -chr T"
  #- "-"
  #- "notCombine"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "notCombine"
  #- "notCombine"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  #- "-"
  - "-"
  #- "'-strand T'" 
  #- "'-strand T -chr T'"
  #- "-"
  #- "notCombine"

regions_mut:
  - "hela_no_overlap_repdomains_windows_201_100"
  - "sns.seq.rep1_int2hi.rfd_plus_hela_repdomains_windows_201_100"
  - "sns.seq.rep1_int2hi.rfd_minus_hela_repdomains_windows_201_100"
  - "sns.seq.rep1_int2initiation.zones_hela_repdomains_windows_201_100"
  - "initiation.zones_int2sns.seq.rep1_hela_repdomains_windows_201_100"
  - "sns.seq.rep1_int2initiation.zones_hela_repdomains_windows_51_100"
  - "sns.seq.rep1.hela_repdomains_no_overlap_windows_201_100"
  - "sns.seq.rep1.hela_repdomains_no_overlap_windows_51_100"


region_mut_file:
  - "hela_no_overlap_repdomains_windows_201_100.bed"
  - "sns.seq.rep1_int2hi.rfd_plus_hela_repdomains_windows_201_100.bed"
  - "sns.seq.rep1_int2hi.rfd_minus_hela_repdomains_windows_201_100.bed"
  - "sns.seq.rep1_int2initiation.zones_hela_repdomains_windows_201_100.bed"
  - "initiation.zones_int2sns.seq.rep1_hela_repdomains_windows_201_100.bed"
  - "sns.seq.rep1_int2initiation.zones_hela_repdomains_windows_51_100.bed"
  - "sns.seq.rep1.hela_repdomains_no_overlap_windows_201_100.bed"
  - "sns.seq.rep1.hela_repdomains_no_overlap_windows_51_100.bed"

region_mut_comb_opt:  
  - "-score T -strand T"
  - "-score T -strand T"
  - "-score T -strand T"
  - "-score T -strand T"
  - "-score T -strand T"
  - "-score T -strand T"
  - "-score T -strand T"
  - "-score T -strand T"