
#### preparing reference genome ####
# genome gencode link
genomeLink: "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/GRCh37.p13.genome.fa.gz"

# genome name with its path
genome: "/home/azgarian/Desktop/genome.fa"

# bowtie2 index path
bowtie2_index: "/home/azgarian/Desktop//Bowtie2/genome"


#### sample pre-analysis ####
XR-seq: true
Damage-seq: true
DNA-seq: true

samples:

  XR:
    - HXA64A1_ATCACG
    - HXA64B7_CAGATC
    - HXE64A2_CGATGT
    - HXE64B8_ACTTGA
    - HXL64A3_TTAGGC
    - HXL64B9_GATCAG
    - HXACA4_TGACCA
    - HXACB10_TAGCTT
    - HXECA5_ACAGTG
    - HXECB11_GGCTAC
    - HXLCA6_GCCAAT
    - HXLCB12_CTTGTA
    - R19026421-2019XR1-Hela15X2_combined_R1
    - R19026421-2019XR1-Hela35X3_combined_R1
    - R19033030-2019XR3-Hela15X7_combined_R1
    - R19033030-2019XR3-Hela35X8_combined_R1 

  DS:
    - NT4H1-CT5H2-HelaD1-5R2h2_combined
    - XT4H1-CT5H2-HelaD3-5R2h2_combined
    - R19029847-HD2TCD4-HelaD1-5R2h1_combined
    - R19029847-HD2TCD4-HelaD3-5R2h1_combined
    - HDA64A1_ATCACG
    - HDA64B19_GTGAAA
    - HDE64A4_TGACCA
    - HDE64B20_GTGGCC
    - HDL64A5_ACAGTG
    - HDL64B22_CGTACG
    - HDACA6_GCCAAT
    - HDACB23_GAGTGG
    - HDECA10_TAGCTT
    - HDECB25_ACTGAT
    - HDLCA12_CTTGTA
    - HDLCB27_ATTCCT

  DNA:
    - R19040024-HelainputD-Hl15R2hID_combined
    - R19040024-HelainputD-Hl0h20JID_combined
    - R19040024-HelainputD-Hl35R2hID_combined

  path: "/cta/groups/adebali/data/repair/backup/submit"


 