#!/bin/env python


#### configuration file ####
configfile: "config_test.yml"

########################

#### desired outputs ####
rule all:
    input:
        "/home/azgarian/Desktop/genome.fa.fai"

########################

#### preparing reference genome ####
rule download_genome:
    output:
        expand("{genome}.gz", genome=config["genome"])
    params:
        expand("{genomeLink}", genomeLink=config["genomeLink"])[0]    
    shell:
        "wget -O {output} {params}"

rule unzip_genome:
    input:
        expand("{genome}.gz", genome=config["genome"])
    output:
        expand("{genome}", genome=config["genome"])
    shell:
        "gunzip {input}"

rule bowtie2_build_index:
    input:
        expand("{genome}", genome=config["genome"])
    output:
        expand("{bowtie2_index}", bowtie2_index=config["bowtie2_index"])
    shell:
        "bowtie2-build {input} {output}"

rule index:
    input:
        expand("{genome}", genome=config["genome"])
    output:
        expand("{genome}.fai", genome=config["genome"])
    shell:
        "samtools faidx {input}"

########################

#### sample pre-analysis ####


#### prepare data sets to intersect ####