name: produceInitiationZones
dependencies:
  - conda-forge::r-base ==3.6
  - bioconda::bioconductor-rsamtools ==2.0.0
  - r::r-hmm ==1.0
  - bioconda::bioconductor-genomicalignments ==1.20.0
  - conda-forge::r-argparser ==0.4
  - bioconda::samtools ==1.10  